- name: Copy mongodb repo
  ansible.builtin.copy:
    src: mongodb.repo
    dest: /etc/yum.repos.d/mongodb.repo
- name: Install mongodb client
  ansible.builtin.package:
    name: mongodb-org-shell
    state: present
- name: get the categories count
  ansible.builtin.command:  mongo --host mongodb.littlesimba.online --quiet --eval 'db = db.getSiblingDB("{{component}}"); db.products.count()'
  register: product_count
- name: load "{{component}}" data
  ansible.builtin.command: mongo --host mongodb.littlesimba.online < /app/schema/"{{component}}".js
  when: product_count.stdout == "0" # keep double quotes